name: 'sonar-quality-gate'
description: 'This plugin will be intergate to CI/CD, get quality code of sonarqube and push report to merge request when has change.'
branding:
  icon: 'award'  
  color: 'green'
inputs:
  login: 
    description: 'The authentication token or login of a SonarQube user with Execute Analysis permission on the project.'
    required: true
  skipScanner: 
    description: 'skip scanner'
    required: false
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'action/Dockerfile'
  args:
    - -D sonar.login=${{ inputs.login }}
    - --skip-scanner=${{ inputs.skipScanner }}